<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><ApplicationIcon>Assets/jtc.ico</ApplicationIcon><TargetFramework>net10.0-windows</TargetFramework><UseWPF>true</UseWPF><EnableWindowsTargeting>true</EnableWindowsTargeting></PropertyGroup><ItemGroup><Resource Include="Assets/jtc-icon.png"/><ProjectReference Include="../JTCStamper.Core/JTCStamper.Core.csproj"/></ItemGroup><ItemGroup><AssemblyMetadata Include="Distribution" Value="Standard" Condition="'$(SelfContained)' == 'true'"/><AssemblyMetadata Include="Distribution" Value="Lite" Condition="'$(SelfContained)' != 'true'"/></ItemGroup></Project>